### ISSUE TITLE
apple test

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/objc-ApplesAndHolidays#3]
I'd never before seen NSPredicate used on array and had to google how to do it to get to the `self` syntax. Maybe before this lab, a simpler challenge to expose students to more of these NSPredicate usages/examples?

@markedwardmurray

**Comment by markedwardmurray** [comment]
yeah, i need to add to the NSPredicate reading about the `self` option for the keypath.

**Comment by markedwardmurray** [comment]
added a note to the NSPredicate reading and a hint to the lab
